<?php
	session_start(); //allows the site to know if the user is logged in or not!
?>
<!doctype html>
<html lang="en">
<head>
	<link rel="stylesheet" href="../stylesheet/main.css"/> <!-- Links to the external stylesheet -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<title>Order Records</title>
</head>
<body>
	<nav>
		<ul>
			<li> <a href="../home/index.php">Home</a> </li>
			<li> <a href="../admin/admin.php">Admin</a> </li>
			<li> <a href="orderRecordsForm.php">Records</a> </li>
			<li> <a href="../credits/credits.php">Credits</a> </li>
			<?php
			if (!isset($_SESSION['logged_in'])) {
			echo"	<li style='float:right'> <a href='../login/login.php'>Login</a> </li>";		//displays if user is not logged in
		} else {
			echo "<li style='float:right'>";
			echo "<a href='../login/logout.php'>";		//displays if user is logged in
			echo $_SESSION['username'];
			echo ":  Log out</a>";
			echo "</li>";
		}
			 ?>
		</ul>
	</nav>
<div id="wrapper">
<?php
/* This code dynamically generates a web page containing a form designed with the html required to display one
checkbox for each of the records currently held in the nmc_records database table has been provided for you in the
assessment section for the module on blackboard. The user can select one or more records that they are interested in
ordering by clicking the checkboxes.
Use the browser to look at the structure of the html generated by the php code. */

$url = "http://unn-izge1.newnumyspace.co.uk/KF5002/assessment/orderRecordsFormInc.php";
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($curl);
curl_close($curl);
echo $result;
?>

<!-- Here you need to add Javascript or a link to a script (.js file) to process the form as required for the assignment -->
<script src="orders.js">

</script>
</div>
</body>
</html>
